=== IraMatsuk/epam_task3_xml/src/main/resources/data/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/papers"
        xmlns:tns="http://www.example.com/papers"
        elementFormDefault="qualified">

    <element name="paper" type="tns:Paper" abstract="true"/>
    <element name="newspaper" type="tns:Newspaper" substitutionGroup="tns:paper"/>
    <element name="magazine" type="tns:Magazine" substitutionGroup="tns:paper"/>
    <element name="booklet" type="tns:Booklet" substitutionGroup="tns:paper"/>
    <element name="papers">
        <complexType>
            <sequence>
                <element ref="tns:paper" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Paper">
        <sequence>
            <element name="title" type="string"/>
            <element name="paper-properties" type="tns:PaperProperties"/>
            <element name="circulation" type="positiveInteger"/>
            <element name="color" type="boolean" default = "false"/>
            <element name="frequency" type="tns:Frequency"/>
        </sequence>
        <attribute name="id" type="tns:PaperID" use="required"/>
        <attribute name="age-category" type="tns:AgeCategory" use="optional"/>
    </complexType>

    <complexType name="Newspaper">
        <complexContent>
            <extension base="tns:Paper">
                <sequence>
                    <element name="subscription-index" type="tns:IndexID"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Magazine">
        <complexContent>
            <extension base="tns:Paper">
                <sequence>
                    <element name="subscription-index" type="tns:IndexID"/>
                    <element name="direction" type="tns:Direction"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Booklet">
        <complexContent>
            <extension base="tns:Paper">
            </extension>
        </complexContent>
    </complexType>

    <complexType name="PaperProperties">
        <sequence>
            <element name="issue" type="positiveInteger"/>
            <element name="pages" type="positiveInteger"/>
            <element name="glossy" type="boolean"/>
            <element name="price" type="tns:Price"/>
            <element name="issue-date" type="date"/>
        </sequence>
    </complexType>

    <simpleType name="PaperID">
        <restriction base="ID">
            <pattern value="\w{1,10}"/>
        </restriction>
    </simpleType>

    <simpleType name="AgeCategory">
        <restriction base="string">
            <enumeration value="adult"/>
            <enumeration value="child"/>
            <enumeration value="all"/>
        </restriction>
    </simpleType>

    <simpleType name="IndexID">
        <restriction base="ID">
            <pattern value="i\d{5}"/>
        </restriction>
    </simpleType>

    <simpleType name="Price">
        <restriction base="double">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>

    <simpleType name="Frequency">
        <restriction base="string">
            <enumeration value="daily"/>
            <enumeration value="weekly"/>
            <enumeration value="monthly"/>
        </restriction>
    </simpleType>

    <simpleType name="Direction">
        <restriction base="string">
            <enumeration value="medicine"/>
            <enumeration value="science"/>
            <enumeration value="sport"/>
            <enumeration value="other"/>
        </restriction>
    </simpleType>
</schema>

=== IraMatsuk/epam_task3_xml/src/main/resources/data/papers.xml
<?xml version="1.0" encoding="UTF-8" ?>

<papers xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xmlns ="http://www.fairycompany.com/papers"
        xsi:schemaLocation = "http://www.fairycompany.com/papers schema.xsd">

    <newspaper age-category="all" website="www.sb.by">
        <title>Советская Беларусь</title>
        <subscription-index>i45891</subscription-index>
        <paper-properties>
            <issue>1814</issue>
            <pages>22</pages>
            <price>3.25</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>50000</circulation>
        <color>false</color>
        <frequency>daily</frequency>
    </newspaper>

    <newspaper age-category="all" website="www.aif.by">
        <title>Аргументы И Факты</title>
        <subscription-index>i13137</subscription-index>
        <paper-properties>
            <issue>1540</issue>
            <pages>28</pages>
            <price>2.60</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>60000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <newspaper age-category="all" website="www.vitbichi.by">
        <title>Вiтьбiчы</title>
        <subscription-index>i78013</subscription-index>
        <paper-properties>
            <issue>3804</issue>
            <pages>16</pages>
            <price>1.45</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>17000</circulation>
        <color>true</color>
        <frequency>daily</frequency>
    </newspaper>

    <newspaper age-category="adult">
        <title>Детективная Газета</title>
        <subscription-index>i15038</subscription-index>
        <paper-properties>
            <issue>1028</issue>
            <pages>28</pages>
            <price>3.70</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>55000</circulation>
        <color>true</color>
        <frequency>monthly</frequency>
    </newspaper>

    <newspaper age-category="all">
        <title>Знамя Юности</title>
        <subscription-index>i18403</subscription-index>
        <paper-properties>
            <issue>780</issue>
            <pages>20</pages>
            <price>1.70</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>12000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <newspaper age-category="all">
        <title>Навука</title>
        <subscription-index>i17038</subscription-index>
        <paper-properties>
            <issue>386</issue>
            <pages>28</pages>
            <price>2.80</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>15000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <newspaper age-category="all">
        <title>Вяжем шьем вышиваем</title>
        <subscription-index>i19025</subscription-index>
        <paper-properties>
            <issue>487</issue>
            <pages>36</pages>
            <price>4.00</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>18000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <newspaper age-category="all" website="www.pvz.by">
        <title>Переходный возраст</title>
        <subscription-index>i63192</subscription-index>
        <paper-properties>
            <issue>780</issue>
            <pages>40</pages>
            <price>4.20</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>18000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <magazine age-category="all" website="www.igromania.ru">
        <title>Игромания</title>
        <subscription-index>i76398</subscription-index>
        <paper-properties>
            <issue>1548</issue>
            <pages>208</pages>
            <price>20.00</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>180000</circulation>
        <direction>other</direction>
    </magazine>

    <magazine age-category="all">
        <title>Speak English</title>
        <subscription-index>i87954</subscription-index>
        <paper-properties>
            <issue>450</issue>
            <pages>110</pages>
            <price>18.00</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>28000</circulation>
        <direction>other</direction>
    </magazine>

    <magazine age-category="child">
        <title>Мурзилка</title>
        <subscription-index>i12380</subscription-index>
        <paper-properties>
            <issue>511</issue>
            <pages>32</pages>
            <price>6.50</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>32000</circulation>
        <direction>other</direction>
    </magazine>

    <magazine age-category="all">
        <title>Cool</title>
        <subscription-index>i20056</subscription-index>
        <paper-properties>
            <issue>1548</issue>
            <pages>63</pages>
            <price>8.50</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>43000</circulation>
        <direction>medicine</direction>
    </magazine>

    <magazine website="www.bolshoisport.ru" age-category="all" >
        <title>Большой Спорт</title>
        <subscription-index>i12354</subscription-index>
        <paper-properties>
            <issue>240</issue>
            <pages>150</pages>
            <price>17.00</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>70000</circulation>
        <direction>sport</direction>
    </magazine>

    <magazine age-category="all">
        <title>Народный доктор</title>
        <subscription-index>i14567</subscription-index>
        <paper-properties>
            <issue>580</issue>
            <pages>98</pages>
            <price>12.00</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>70000</circulation>
        <direction>medicine</direction>
    </magazine>

    <magazine age-category="all" website="www.internauka.org">
        <title>Интернаука</title>
        <subscription-index>i45781</subscription-index>
        <paper-properties>
            <issue>360</issue>
            <pages>68</pages>
            <price>23.50</price>
            <issue-date>2021-11-01</issue-date>
        </paper-properties>
        <circulation>280000</circulation>
        <direction>science</direction>
    </magazine>


<!--    <newspaper id="ID1" publication-date="1894-10-10">-->
<!--        <title>The Wall Street Journal</title>-->
<!--        <monthly>yes</monthly>-->
<!--        <paper-properties>-->
<!--            <color>true</color>-->
<!--            <pages>58</pages>-->
<!--            <glossy>false</glossy>-->
<!--        </paper-properties>-->
<!--        <subscription-index>0099-9660</subscription-index>-->
<!--    </newspaper>-->

<!--    <newspaper id="ID2" publication-date="1864-12-10">-->
<!--        <title>The New York Times</title>-->
<!--        <monthly>yes</monthly>-->
<!--        <paper-properties>-->
<!--            <color>true</color>-->
<!--            <pages>70</pages>-->
<!--            <glossy>false</glossy>-->
<!--        </paper-properties>-->
<!--        <subscription-index>0362-4331</subscription-index>-->
<!--    </newspaper>-->

<!--    <newspaper id="ID3" publication-date="1917-08-09">-->
<!--        <title>Zviazda</title>-->
<!--        <monthly>yes</monthly>-->
<!--        <paper-properties>-->
<!--            <color>false</color>-->
<!--            <pages>10</pages>-->
<!--            <glossy>false</glossy>-->
<!--        </paper-properties>-->
<!--        <subscription-index>63850</subscription-index>-->
<!--    </newspaper>-->


<!--    <magazine id="ID4" publication-date="1812-01-01">-->
<!--        <title>The New England Journal of Medicine</title>-->
<!--        <monthly>no</monthly>-->
<!--        <paper-properties>-->
<!--            <color>true</color>-->
<!--            <pages>70</pages>-->
<!--            <glossy>true</glossy>-->
<!--        </paper-properties>-->
<!--        <subscription-index>0028-4793</subscription-index>-->
<!--    </magazine>-->

<!--    <booklet id="ID5" publication-date="2016-11-19">-->
<!--        <title>Poznay svoyu Belarus</title>-->
<!--        <monthly>no</monthly>-->
<!--        <paper-properties>-->
<!--            <color>true</color>-->
<!--            <pages>38</pages>-->
<!--            <glossy>true</glossy>-->
<!--        </paper-properties>-->
<!--    </booklet>-->
</papers>
